### ISSUE TITLE
IOS 14.5 Update for CCCalc

### ISSUE THREAD

**Issue by Ajslapss** [Halo-Michael/halo-michael.github.io#15]
Hey I've been trying to install CCCalc on my iPhone 11 iOS 14.5 Unc0ver Jailbreak and my phone continues to go into safe mode. I noticed that you edited the files so it would be compatible with iOS 14. I'm manually install the updated files that you've created but I'm not sure where and which folder you would add them in. so far I've put them in library/mobilesubstrate/dynamiclibraries but it still crashes back into safe mode when I restring. do you have any suggestions?

**Comment by Halo-Michael** [comment]
CCCalc is not my project/
