### ISSUE TITLE
iPad Pro 11 Screen optimization

### ISSUE THREAD

**Issue by thefakesound** [Halo-Michael/halo-michael.github.io#2]
Could you please compile .ipa to support newer devices resolutions? Thanks

**Comment by thefakesound** [comment]
You should use Launch Storyboards instead of Launch Images btw

**Comment by Halo-Michael** [comment]
It's totally not my issues, I'm just built the ipa. If you have any issues with PPSSPP, please check here: https://github.com/hrydgard/ppsspp/issues
Now close it.

**Comment by thefakesound** [comment]
No, It is not ppsspp issue it is building ipa issue with outdated parameters.

**Comment by thefakesound** [comment]
![9512D32F-B1E6-42A3-86A0-1C358E8B68A4](https://user-images.githubusercontent.com/56938252/69262448-ede2dd00-0bdc-11ea-8022-ed2ec0fa60d6.png)

**Comment by Halo-Michael** [comment]
It's NOT MY ISSUE. All the cmake build parameters is written by PPSSPP tesm.
https://github.com/hrydgard/ppsspp/issues/11677

**Comment by thefakesound** [comment]
Sorry, now I got it. Thanks!
